name: 'Setup Zig'
description: 'Download Zig installation'
inputs:
  version:
    description: 'Zig version to install'
    required: false
    default: '0.15.1'

runs:
  using: 'composite'
  steps:
    - uses: actions/cache@v4
      with:
        path: .zig-install
        key: zig-${{ inputs.version }}-${{ runner.os }}-${{ runner.arch }}

    - shell: bash
      run: ${GITHUB_ACTION_PATH}/install-zig.sh ${{ inputs.version }}
