name: CI

on:
  push:
    branches: [main]
    paths:
      - 'src/**/*.zig'
  pull_request:
    branches: [main]
    paths:
      - 'src/**/*.zig'
  schedule:
    - cron: '0 6 * * 1'  # Every Monday at 6 AM UTC

jobs:
  test:
    name: Tests

    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        zig-version: ['0.14.1']

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: ./.github/actions/setup-zig
      with:
        version: ${{ matrix.zig-version }}

    - uses: actions/cache@v4
      with:
        path: .zig-cache
        key: zig-cache-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('build.zig', 'build.zig.zon') }}

    - run: zig build test --summary all

    - run: zig build luau-compile -- --help
    - run: zig build luau-analyze -- --help

  format:
    name: Formatting

    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: ./.github/actions/setup-zig
      with:
        version: '0.14.1'

    - run: zig build check-fmt
      shell: bash

  lint:
    name: Linter

    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - run: curl -fsSL https://raw.githubusercontent.com/DonIsaac/zlint/refs/heads/main/tasks/install.sh | bash
    - run: zlint

  cover:
    name: Coverage

    timeout-minutes: 30
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    env:
      KCOV_VERSION: v42

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install kcov
      run: |
        gh release download ${{ env.KCOV_VERSION }} --repo SimonKagstrom/kcov --pattern 'kcov-amd64.tar.gz'
        tar -xzf kcov-amd64.tar.gz
        sudo cp -r usr/local/* /usr/local/
        rm -rf kcov-amd64.tar.gz usr/
        sudo apt-get install -y kcov

    - run: zig build test -Dcoverage

    - uses: codecov/codecov-action@v5
      with:
        use_oidc: true
        directory: ./zig-out/coverage