name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Tests

    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        zig-version: ['0.14.1']

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: ./.github/actions/setup-zig
      with:
        version: ${{ matrix.zig-version }}

    - uses: actions/cache@v4
      with:
        path: .zig-cache
        key: zig-cache-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('build.zig', 'build.zig.zon') }}

    - run: zig build test --summary all

    - run: zig build luau-compile -- --help
    - run: zig build luau-analyze -- --help

  format:
    name: Formatting
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: ./.github/actions/setup-zig
      with:
        version: '0.14.1'

    - run: zig build check-fmt
      shell: bash

