name: CI

on:
  push:
    branches: [main]
    paths:
      - '**/*.zig'
      - '.github/workflows/*.yml'
      - 'build.zig.zon'
  pull_request:
    branches: [main]
    paths:
      - '**/*.zig'
      - '.github/workflows/*.yml'
      - 'build.zig.zon'
  schedule:
    - cron: '0 6 * * 1'  # Every Monday at 6 AM UTC

jobs:
  test:
    name: Tests

    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        zig-version: ['0.14.1']

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: ./.github/actions/setup-zig
      with:
        version: ${{ matrix.zig-version }}

    - uses: actions/cache@v4
      with:
        path: .zig-cache
        key: zig-cache-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('build.zig', 'build.zig.zon') }}

    - run: zig build test --summary all
    - run: zig build test -Dvector-size=3 --summary all

    - run: zig build luau-compile -- --help
    - run: zig build luau-analyze -- --help

    - run: zig build guided-tour

  format:
    name: Formatting

    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: ./.github/actions/setup-zig
      with:
        version: '0.14.1'

    - run: zig build check-fmt
      shell: bash

  lint:
    name: Linter

    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - run: curl -fsSL https://raw.githubusercontent.com/DonIsaac/zlint/refs/heads/main/tasks/install.sh | bash
    - run: zlint

  cover:
    name: Coverage

    timeout-minutes: 30
    runs-on: ubuntu-22.04

    permissions:
      contents: read # Remove after making repo public
      id-token: write

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install kcov
      run: |
        sudo apt-get update
        sudo apt-get install -y kcov
        kcov --version

    - name: Install Zig
      uses: ./.github/actions/setup-zig
      with:
        version: '0.14.1'

    - uses: actions/cache@v4
      with:
        path: .zig-cache
        key: zig-cache-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('build.zig', 'build.zig.zon') }}

    - name: Tests coverage
      run: |
        mkdir -p zig-out/coverage
        zig build test -Dcoverage

    - uses: codecov/codecov-action@v5
      with:
        use_oidc: true
        directory: zig-out/coverage/test/