name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 6 * * 1'  # Every Monday at 6 AM UTC

jobs:
  test:
    name: Tests

    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        zig-version: ['0.14.1']

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: ./.github/actions/setup-zig
      with:
        version: ${{ matrix.zig-version }}

    - uses: actions/cache@v4
      with:
        path: .zig-cache
        key: zig-cache-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('build.zig', 'build.zig.zon') }}

    - run: zig build test --summary all

    - run: zig build luau-compile -- --help
    - run: zig build luau-analyze -- --help

  format:
    name: Formatting

    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: ./.github/actions/setup-zig
      with:
        version: '0.14.1'

    - run: zig build check-fmt
      shell: bash

  lint:
    name: Linter

    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - run: curl -fsSL https://raw.githubusercontent.com/DonIsaac/zlint/refs/heads/main/tasks/install.sh | bash
    - run: zlint
