name: Docs

on:
  push:
    branches: [main]
    paths:
      - 'src/**/*.zig'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    name: Deploy

    runs-on: ubuntu-latest
    timeout-minutes: 30

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: ./.github/actions/setup-zig
      with:
        version: 0.14.1

    - name: Build docs
      run: |
        # I don't know why this is needed for the docs to succeed on CI, but otherwise it consistently fails with:
        #   error: unable to open directory '...': FileNotFound
        # See https://github.com/mxpv/luaz/actions/runs/16698403816/job/47265761593
        for i in {1..3}; do
          if zig build docs; then
            break
          fi
          echo "Attempt $i failed, retrying..."
          sleep 2
        done

    - uses: actions/configure-pages@v5
    - uses: actions/upload-pages-artifact@v3
      with:
        path: ./zig-out/docs/

    - id: deployment
      uses: actions/deploy-pages@v4
